package site.gaoyisheng.dao;

import java.util.List;

import site.gaoyisheng.pojo.Question;

public interface QuestionMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table question
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table question
	 *
	 * @mbg.generated
	 */
	int insert(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table question
	 *
	 * @mbg.generated
	 */
	int insertSelective(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table question
	 *
	 * @mbg.generated
	 */
	Question selectByPrimaryKey(Integer id);

	List<Question> selectByTeamId(Integer team_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table question
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table question
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Question record);
}