package site.gaoyisheng.dao;

import java.util.List;
import java.util.Map;

import site.gaoyisheng.pojo.User;

public interface UserMapper {
	
	/**
	 * 不区分身份，返回所有用户.
	 * TODO
	 * @return
	 */
	List<User> selectAllUser();
	
	/**
	 * 按身份查询.
	 * TODO
	 * @param identity
	 * @return
	 */
	List<User> selectAllUserByIdentity(String identity);
	
	/**
	 * 按身份查询.
	 * 除identity外,所有
	 * TODO
	 * @param identity
	 * @return
	 */
	List<User> selectAllUserExceptIdentity(String identity);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);
    
    /**
     * .
     * TODO
     * @param record
     * @return 返回的并不是id,而是 0,1 = false,true
     */
    int insertCacheId(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);
    
    /**
     * 。
     * login
     */
    User selectByNumberAndPassword(Map<String, Object> param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
}