package site.gaoyisheng.pojo;

public class Achievement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.student_id
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.score
     *
     * @mbg.generated
     */
    private Short score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.answercode
     *
     * @mbg.generated
     */
    private String answercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.filepath
     *
     * @mbg.generated
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievement.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.id
     *
     * @return the value of achievement.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.id
     *
     * @param id the value for achievement.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.question_id
     *
     * @return the value of achievement.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.question_id
     *
     * @param questionId the value for achievement.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.student_id
     *
     * @return the value of achievement.student_id
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.student_id
     *
     * @param studentId the value for achievement.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.score
     *
     * @return the value of achievement.score
     *
     * @mbg.generated
     */
    public Short getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.score
     *
     * @param score the value for achievement.score
     *
     * @mbg.generated
     */
    public void setScore(Short score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.answercode
     *
     * @return the value of achievement.answercode
     *
     * @mbg.generated
     */
    public String getAnswercode() {
        return answercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.answercode
     *
     * @param answercode the value for achievement.answercode
     *
     * @mbg.generated
     */
    public void setAnswercode(String answercode) {
        this.answercode = answercode == null ? null : answercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.result
     *
     * @return the value of achievement.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.result
     *
     * @param result the value for achievement.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.filepath
     *
     * @return the value of achievement.filepath
     *
     * @mbg.generated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.filepath
     *
     * @param filepath the value for achievement.filepath
     *
     * @mbg.generated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievement.version
     *
     * @return the value of achievement.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievement.version
     *
     * @param version the value for achievement.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}