package site.gaoyisheng.pojo;

import java.util.Date;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.team_id
     *
     * @mbg.generated
     */
    private Integer teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.deadtime
     *
     * @mbg.generated
     */
    private Date deadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.diffculty
     *
     * @mbg.generated
     */
    private Short diffculty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answercode
     *
     * @mbg.generated
     */
    private String answercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerdetail
     *
     * @mbg.generated
     */
    private String answerdetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.name
     *
     * @return the value of question.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.name
     *
     * @param name the value for question.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.team_id
     *
     * @return the value of question.team_id
     *
     * @mbg.generated
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.team_id
     *
     * @param teamId the value for question.team_id
     *
     * @mbg.generated
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.detail
     *
     * @return the value of question.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.detail
     *
     * @param detail the value for question.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.deadtime
     *
     * @return the value of question.deadtime
     *
     * @mbg.generated
     */
    public Date getDeadtime() {
        return deadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.deadtime
     *
     * @param deadtime the value for question.deadtime
     *
     * @mbg.generated
     */
    public void setDeadtime(Date deadtime) {
        this.deadtime = deadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.diffculty
     *
     * @return the value of question.diffculty
     *
     * @mbg.generated
     */
    public Short getDiffculty() {
        return diffculty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.diffculty
     *
     * @param diffculty the value for question.diffculty
     *
     * @mbg.generated
     */
    public void setDiffculty(Short diffculty) {
        this.diffculty = diffculty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.result
     *
     * @return the value of question.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.result
     *
     * @param result the value for question.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answercode
     *
     * @return the value of question.answercode
     *
     * @mbg.generated
     */
    public String getAnswercode() {
        return answercode;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answercode
     *
     * @param answercode the value for question.answercode
     *
     * @mbg.generated
     */
    public void setAnswercode(String answercode) {
        this.answercode = answercode == null ? null : answercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerdetail
     *
     * @return the value of question.answerdetail
     *
     * @mbg.generated
     */
    public String getAnswerdetail() {
        return answerdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerdetail
     *
     * @param answerdetail the value for question.answerdetail
     *
     * @mbg.generated
     */
    public void setAnswerdetail(String answerdetail) {
        this.answerdetail = answerdetail == null ? null : answerdetail.trim();
    }
    
    @Override
 	public String toString() {
 		return "Question [id=" + id + ", name=" + name + ", teamId=" + teamId + ", detail=" + detail + ", deadtime="
 				+ deadtime + ", diffculty=" + diffculty + ", result=" + result + ", answercode=" + answercode
 				+ ", answerdetail=" + answerdetail + "]";
 	}
    
}