package site.gaoyisheng.pojo;

import java.io.Serializable;

public class User implements Serializable{
	private static final long serialVersionUID = -48880431122099985L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.number
	 *
	 * @mbg.generated
	 */
	private String number;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.password
	 *
	 * @mbg.generated
	 */
	private String password;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.identity
	 *
	 * @mbg.generated
	 */
	private String identity;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.name
	 *
	 * @mbg.generated
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.idcard
	 *
	 * @mbg.generated
	 */
	private String idcard;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.team_id
	 *
	 * @mbg.generated
	 */
	private Integer teamId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.email
	 *
	 * @mbg.generated
	 */
	private String email;

	public User() {
		super();
	}
	
	public User(String number, String password, String identity, String name, String idcard, Integer teamId,
			String email) {
		super();
		this.number = number;
		this.password = password;
		this.identity = identity;
		this.name = name;
		this.idcard = idcard;
		this.teamId = teamId;
		this.email = email;
	}

	public User(Integer id, String number, String password, String identity, String name, String idcard, Integer teamId,
			String email) {
		super();
		this.id = id;
		this.number = number;
		this.password = password;
		this.identity = identity;
		this.name = name;
		this.idcard = idcard;
		this.teamId = teamId;
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.id
	 *
	 * @return the value of user.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.id
	 *
	 * @param id
	 *            the value for user.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.number
	 *
	 * @return the value of user.number
	 *
	 * @mbg.generated
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.number
	 *
	 * @param number
	 *            the value for user.number
	 *
	 * @mbg.generated
	 */
	public void setNumber(String number) {
		this.number = number == null ? null : number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.password
	 *
	 * @return the value of user.password
	 *
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.password
	 *
	 * @param password
	 *            the value for user.password
	 *
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.identity
	 *
	 * @return the value of user.identity
	 *
	 * @mbg.generated
	 */
	public String getIdentity() {
		return identity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.identity
	 *
	 * @param identity
	 *            the value for user.identity
	 *
	 * @mbg.generated
	 */
	public void setIdentity(String identity) {
		this.identity = identity == null ? null : identity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.name
	 *
	 * @return the value of user.name
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.name
	 *
	 * @param name
	 *            the value for user.name
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.idcard
	 *
	 * @return the value of user.idcard
	 *
	 * @mbg.generated
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.idcard
	 *
	 * @param idcard
	 *            the value for user.idcard
	 *
	 * @mbg.generated
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard == null ? null : idcard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.team_id
	 *
	 * @return the value of user.team_id
	 *
	 * @mbg.generated
	 */
	public Integer getTeamId() {
		return teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.team_id
	 *
	 * @param teamId
	 *            the value for user.team_id
	 *
	 * @mbg.generated
	 */
	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.email
	 *
	 * @return the value of user.email
	 *
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.email
	 *
	 * @param email
	 *            the value for user.email
	 *
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", number=" + number + ", password=" + password + ", identity=" + identity + ", name="
				+ name + ", idcard=" + idcard + ", teamId=" + teamId + ", email=" + email + "]";
	}
}